name = "minirest"
description = "Minimalist Ada REST client library"
version = "0.2-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

licenses = "MIT"
tags = ["rest"]
website = "https://github.com/mosteo/minirest"

[[depends-on]]
aaa = "~0.2.1"
curl = "*"
