name = "minirest"
description = "Minimalistic Ada REST client library"
version = "0.1.0"

authors = ["Alejandro R. Mosteo"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[depends-on]]
aaa = "*"
