name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update && 
        sudo apt-get install gnat gprbuild

    - name: Set up Alire
      uses: alire-project/setup-alire@latest-stable

    - name: Build
      run: |
        alr update -f -n    # force to accept curl missing
        alr with --versions
        alr build
